apiVersion: skaffold/v2beta6
kind: Config
build:
  artifacts:
    - image: stock-prices-collector-processor-sink
      context: ../..
      jib:
        project: services:stock-prices-collector-processor-sink:service

deploy:
  kubeContext: minikube

profiles:
  - name: minikube
    activation:
      - kubeContext: minikube
        command: dev
    deploy:
      kubeContext: minikube
      helm:
        releases:
          - name: stock-prices-collector-processor-sink
            chartPath: deployment
            artifactOverrides:
              image.repository: stock-prices-collector-processor-sink
            valuesFiles:
              - ../../environments/minikube.yml
            setValues:
              replicaCount: 1
              ingress.albIngressController.inboundCidr: 0.0.0.0/8
              ingress.albIngressController.environment: "MINIKUBE"
              ingress.albIngressController.acmCertificateArn: "unused"
              ingress.externalDns: "stock-prices-collector-processor-sink"
              datadog.applicationPerformanceMonitoring.environment: "minikube"
  - name: dev
    activation:
      - kubeContext: arn:aws:eks:us-east-2:234424433652:cluster/EksClusterK8s
    deploy:
     kubeContext: arn:aws:eks:us-east-2:234424433652:cluster/EksClusterK8s
     helm:
       releases:
         - name: stock-prices-collector-processor-sink
           chartPath: deployment
           namespace: default
           valuesFiles:
              - ../../environments/dev.yml
           setValues:
             replicaCount: 1
             requestMemory: 0.2Gi
           artifactOverrides:
              image.repository: stock-prices-collector-processor-sink
