apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: store
spec:
  storageClassName: "{{.Values.env.STORAGE_CLASS}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{.Values.env.STORAGE_SIZE}}"
