apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb-local
  template:
    metadata:
      labels:
        app: dynamodb-local
    spec:
      securityContext:
        runAsUser: 0  # Set the user ID to 0 (root)
      containers:
        - name: dynamodb-local
          image: amazon/dynamodb-local:1.16.0
          securityContext:
            windowsOptions:
              runAsUserName: root
          envFrom:
            - configMapRef:
                name: dynamodb-data
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}


