apiVersion: v1
kind: Service
metadata:
  name: market-stock-api

spec:
  selector:
    app: market-stock-api
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.nodePort }}
      protocol: TCP
      name: httpx