#BaseReference:https://github.com/confluentinc/cp-helm-charts/blob/master/charts/cp-kafka/values.yaml
#--https://github.com/confluentinc/cp-helm-charts/tree/master/charts
cp-zookeeper:
  enabled: true
  prometheus:
    jmx:
      enabled: false
  servers: 1

cp-kafka:
  enabled: true
  prometheus:
    jmx:
      enabled: false
  brokers: 1
  configurationOverrides:
    "offsets.topic.replication.factor": 1
    "default.replication.factor": 1
    "confluent.metrics.reporter.topic.replicas": 1
    "transaction.state.log.replication.factor": 1
    "transaction.state.log.min.isr": 1
    "kafkastore.topic.replication.factor": 1
    ##AdvertisedlistenerswillusethefirstListenerPortvalueasit'sdefaultunlessoverriddenhere.
    ##Setting"advertised.listeners"hereappendsto"PLAINTEXT://${POD_NAME}.cp-helm-charts-cp-kafka-headless.${POD_NAMESPACE}:9092,"
    "advertised.listeners": |-
      EXTERNAL://${HOST_IP}:31090
    "listener.security.protocol.map": |-
      PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
  nodeport:
    enabled: true
    servicePort: 19092
    firstListenerPort: 31090

cp-schema-registry:
  enabled: false

cp-kafka-rest:
  enabled: false

cp-ksql-server:
  enabled: false

cp-control-center:
  enabled: false