/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.market.stock.api;

import com.market.stock.Stock;
import com.market.stock.repository.StockRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.time.LocalDateTime;
import java.time.ZonedDateTime;

@SpringBootApplication
public class MarketStockApi implements CommandLineRunner {

    @Autowired private StockRepository stockRepository;

    public static void main(String[] args) {
        SpringApplication.run(MarketStockApi.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
    }
}
